Issue #119 - remove outgoing commits in between processing libraries
mozilla-services/updatebot pull request #132
Opened 2021-01-25 15:35 UTC by metalcanine

Going to test this in holly to make sure it both doesn't blow up and that `hg strip` is available before requesting review

2021-01-25 16:51 UTC, tomrittervg commented
We should put a bug on file to add a test for this; would would be non-trivial right now because when we run our tests we don't actually mach vendor anything...

2021-01-26 14:45 UTC, metalcanine commented
so it turns out we don't have strip available, so I need to either find a way to make it available or come up with a different plan

2021-01-26 14:57 UTC, tomrittervg commented
Try enabling it here https://searchfox.org/mozilla-central/source/taskcluster/docker/updatebot/hgrc

2021-03-09 21:31 UTC, tomrittervg commented on automation.py
> +        self.logger.log("Removing any outgoing commits before moving on.")
This needs `, level=LogLevel.Info`

2021-03-09 21:41 UTC, tomrittervg requested changes
This is going to need rebasing now that this code has moved to tasks/vendoring

2021-03-10 19:08 UTC, tomrittervg approved these changes

2021-03-11 13:44 UTC, merged