2021 02 23 commitalert work
mozilla-services/updatebot pull request #152
Opened 2021-02-24 21:18 UTC by tomrittervg

the base branch of this PR is another branch so that the diff is easier to review (you won't see the commits in the branch.) But when we finally merge it it should be changed to merge into master.

2021-02-25 18:40 UTC, metalcanine requested changes
A question about a comment and a needed comment in one spot to help ourselves out in the future, but otherwise looks great!

2021-02-25 18:40 UTC, metalcanine commented on automation.py
> +        # In this function we have not set up our robust logging facilities yet
I'm not sure what this means, is it that we haven't moved from our basic logger to the full loggingprovider yet?

2021-02-25 18:40 UTC, metalcanine commented on automation.py
> +                self.logger.log("The FF version we pulled from the repo is < 87: %s" % ff_version, level=LogLevel.Fatal)
Can we add a comment on why < 87 is gated from running updatebot?

2021-02-25 18:40 UTC, metalcanine commented on components/libraryprovider.py
> +        if self._libraries is None:
Oh neat! I didn't realize that caching the result was going to be that small of a change. Nice!

2021-02-27 05:24 UTC, tomrittervg commented
I've completly changed this branch to be commits that are relatively concrete and isolated from the work of creating a commit alert task.

2021-03-01 23:14 UTC, metalcanine approved these changes
Looks great, thanks!

2021-03-04 19:23 UTC, merged